import os
import time
from datetime import datetime
from dotenv import load_dotenv
import pymysql
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import oracledb

# .env 파일 로드
load_dotenv()

# --- [DB 접속 함수 정의] ---

def get_mysql_admin_conn():
    # DB명을 지정하지 않고 접속 (DB 생성을 위해)
    return pymysql.connect(
        host=os.getenv("MYSQL_HOST"),
        port=int(os.getenv("MYSQL_PORT")),
        user=os.getenv("MYSQL_USER"),
        password=os.getenv("MYSQL_PASSWORD"),
        autocommit=True
    )

def get_pg_admin_conn():
    # 기본 postgres DB에 접속 (새 DB 생성을 위해)
    return psycopg2.connect(
        host=os.getenv("PG_HOST"),
        port=os.getenv("PG_PORT"),
        user=os.getenv("PG_USER"),
        password=os.getenv("PG_PASSWORD"),
        dbname="postgres"
    )

def get_ora_conn():
    # Oracle은 계정이 곧 스키마이므로 기존 정보로 접속
    return oracledb.connect(
        user=os.getenv("ORA_USER"),
        password=os.getenv("ORA_PASSWORD"),
        dsn=os.getenv("ORA_DSN")
    )

# --- [주요 기능 함수] ---

def setup_databases():
    """1. DB 및 테이블 생성 기능"""
    print("\n" + "="*50)
    print("   🛠️  시스템 초기 설정 (DB 및 테이블 생성)")
    print("="*50)

    # --- MySQL 설정 ---
    try:
        m_conn = get_mysql_admin_conn()
        m_cur = m_conn.cursor()
        m_cur.execute("CREATE DATABASE IF NOT EXISTS db_monitor")
        m_cur.execute("USE db_monitor")
        m_cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ MySQL: 'db_monitor' DB 및 'users' 테이블 준비 완료")
        m_conn.close()
    except Exception as e:
        print(f"❌ MySQL 에러: {e}")

    # --- PostgreSQL 설정 ---
    try:
        p_admin_conn = get_pg_admin_conn()
        p_admin_conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        p_admin_cur = p_admin_conn.cursor()
        p_admin_cur.execute("SELECT 1 FROM pg_catalog.pg_database WHERE datname = 'db_monitor'")
        if not p_admin_cur.fetchone():
            p_admin_cur.execute("CREATE DATABASE db_monitor")
            print("✅ PostgreSQL: 'db_monitor' DB 생성 성공")
        
        # 새 DB에 접속해서 테이블 생성
        p_target_conn = psycopg2.connect(
            host=os.getenv("PG_HOST"), port=os.getenv("PG_PORT"),
            user=os.getenv("PG_USER"), password=os.getenv("PG_PASSWORD"),
            dbname="db_monitor"
        )
        p_target_cur = p_target_conn.cursor()
        p_target_cur.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        p_target_conn.commit()
        print("✅ PostgreSQL: 'users' 테이블 준비 완료")
        p_target_conn.close()
        p_admin_conn.close()
    except Exception as e:
        print(f"❌ PostgreSQL 에러: {e}")

    # --- Oracle 설정 ---
    try:
        o_conn = get_ora_conn()
        o_cur = o_conn.cursor()
        try:
            o_cur.execute("""
                CREATE TABLE users (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(50) NOT NULL,
                    email VARCHAR2(100),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            o_conn.commit()
            print("✅ Oracle: 'users' 테이블 생성 성공")
        except oracledb.DatabaseError as e:
            if e.args[0].code == 955: # ORA-00955: name is already used
                print("✅ Oracle: 'users' 테이블이 이미 존재합니다.")
        o_conn.close()
    except Exception as e:
        print(f"❌ Oracle 에러: {e}")

def insert_test_data():
    """2. 테스트 데이터 삽입 기능"""
    print("\n" + "-"*50)
    name = input("추가할 사용자 이름: ")
    email = input("추가할 이메일: ")

    # MySQL 삽입
    try:
        conn = pymysql.connect(host=os.getenv("MYSQL_HOST"), port=int(os.getenv("MYSQL_PORT")),
                               user=os.getenv("MYSQL_USER"), password=os.getenv("MYSQL_PASSWORD"), db="db_monitor")
        cur = conn.cursor()
        cur.execute("INSERT INTO users (username, email) VALUES (%s, %s)", (name, email))
        conn.commit()
        print("✅ MySQL: 데이터 저장 완료")
        conn.close()
    except Exception as e: print(f"❌ MySQL 삽입 실패: {e}")

    # PostgreSQL 삽입
    try:
        conn = psycopg2.connect(host=os.getenv("PG_HOST"), port=os.getenv("PG_PORT"),
                                user=os.getenv("PG_USER"), password=os.getenv("PG_PASSWORD"), dbname="db_monitor")
        cur = conn.cursor()
        cur.execute("INSERT INTO users (username, email) VALUES (%s, %s)", (name, email))
        conn.commit()
        print("✅ PostgreSQL: 데이터 저장 완료")
        conn.close()
    except Exception as e: print(f"❌ PostgreSQL 삽입 실패: {e}")

    # Oracle 삽입
    try:
        conn = get_ora_conn()
        cur = conn.cursor()
        cur.execute("INSERT INTO users (username, email) VALUES (:1, :2)", (name, email))
        conn.commit()
        print("✅ Oracle: 데이터 저장 완료")
        conn.close()
    except Exception as e: print(f"❌ Oracle 삽입 실패: {e}")

# --- [메인 루프] ---

def main():
    while True:
        print("\n" + "### DB 통합 관리 매니저 ###")
        print("1. 전체 DB/테이블 초기화 설정")
        print("2. 테스트 데이터 삽입 (3사 공통)")
        print("3. 종료")
        
        choice = input("\n메뉴 선택: ")
        
        if choice == '1':
            setup_databases()
        elif choice == '2':
            insert_test_data()
        elif choice == '3':
            print("프로그램을 종료합니다.")
            break
        else:
            print("번호를 다시 확인해주세요.")

if __name__ == "__main__":
    main()